version: '3'

services:

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    #    hostname: redis-cache
    command: redis-server --port 6379
    ports:
      - "6379:6379"
  redis-session:
    image: redis:latest
    container_name: redis-session
    #    hostname: redis-session
    command: redis-server --port 6380
    ports:
      - "6380:6380"

