version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    #    hostname: redis-cache
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - test_network
  redis-session:
    image: redis:latest
    container_name: redis-session
    #    hostname: redis-session
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    networks:
      - test_network

  application:
    container_name: ward-study
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
      - redis-cache
      - redis-session
    networks:
      - test_network

networks:
  test_network:
