
server:
  port: 8081

spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  batch:
    job:
      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
#  main:
#    web-application-type: none

  jackson:
    serialization:
      fail-on-empty-beans: false

  session:
    store-type: redis

  redis:
    cache:
      host: redis-cache
      port: 6379
    session:
      host: redis-session
      port: 6380

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ehtjd33@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug

app:
  firebase-configuration-file: ./file-storage-68596-firebase-adminsdk-5bv5f-260ab6cc65.json
  firebase-bucket: file-storage-68596.appspot.com
